### PR TITLE
Fixes #30303 - Make webhooks audited

### PR DESCRIPTION
**Pull request by ofedoren**
@lzap, not sure if I need to do some additional changes... Although audit records are being added just fine.

### CODE REVIEW

**Review by lzap — APPROVED** [review]
Looks like webhook_template does have it already. Okay.

**Comment by lzap** [comment]
It works fine, when I click on webhook name in Audits, it does not filter it properly but this is not our problem I guess.

**Comment by ofedoren** [comment]
@lzap, I've noticed that somehow there is no `webhook` in `auditable_type`s. Which is quite weird. But per https://github.com/theforeman/foreman/blob/da7bca25f644a31f0f7b45194cc5fc6102c41cc3/app/models/concerns/audit_search.rb#L49 this should work in production mode. I've tried to run local setup in production and at least for API requests it works just fine.

**Comment by lzap** [comment]
This is very likely eager loading which is performed in production, in development Rails load classes as they are used (autoloading).

**Pull request merged**
