### PR TITLE
Add packit config

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Yes, this will need to have all the scl references dropped from the rpm spec, smiliarly to what @ekohl just suggested in https://github.com/theforeman/foreman-packaging/pull/9431#pullrequestreview-1443884058

**Comment by ofedoren** [comment]
Should be fixed by https://github.com/theforeman/foreman-packaging/pull/9440

**Review by evgeni — APPROVED** [review]

**Comment by ofedoren** [comment]
Thanks all :heart:

**Pull request merged**
