### PR TITLE
Fixes #32939 - Remove plugin toasts implementation

### PR DESCRIPTION
**Pull request by laviro**
The toasts are being moved to the root of the app in https://github.com/theforeman/foreman/pull/8618
so it would be easier to trigger instead of creating the whole boilerplate for it in the plugin.
cc @amirfefer @ofedoren

depends on https://github.com/theforeman/foreman/pull/8618

### CODE REVIEW

**Review by amirfefer — APPROVED** [review]
Thanks @laviro 👍

**Review by tbrisker — APPROVED** [review]
Thanks @laviro ! core has been merged

**Comment by tbrisker** [comment]
@lzap the toasts were added in core in 3.0, so it's safe to pull into 3.0 but not 2.5.

**Comment by lzap** [comment]
I see, but this PR actually removes toast arguments, so is my understanding correct that this patch actually enables 2.5 compatibility? :-)

**Comment by lzap** [comment]
Oh scratch that I understand now, 3.0 only.

**Pull request merged**
