### PR TITLE
Fixes #30302 - Add default roles for webhooks

### PR DESCRIPTION
**Pull request by ofedoren**
Added taxonomies support for webhooks and 2 default roles as per issue. The rest is small fixes or making rubocop happy.

### CODE REVIEW

**Comment by timogoebel** [comment]
Why would you need taxonomies with webhooks? What happens if I limit a webhook to a specific org? Do I only get events for models that belong to that particular org?

**Comment by ofedoren** [comment]
@timogoebel, at the moment there is no much advantages with taxonomies for webhooks. For now it only applies on users (a user in loc_1 and org_1 can view/modify webhooks from loc_1 and org_1 only).

**Comment by timogoebel** [comment]
Does that mean I can see data from foreign orgs just by configuring a webhook?

**Comment by lzap** [comment]
The RM ticket was a copy of Red Hat PM requirement - all features must have taxonomy implemented. I did not think about it, just blindly copied - I was not expecting us working on this anytime soon. Current foreman_hooks do not support taxonomies and I thought that we would take a look on this later.

We can't implement this just for webhooks and not for the payload - this would create false expectation. We'd need to make taxonomy a mandatory payload option. I think it's a bit too early now and frankly, if you ask me, I'd rather not implement this at all.

I'd assume that at this point we would only create permissions: create, view, update, destroy webhooks (and templates) so administrator can define who can actually operate on those. And in the documentation we need to state that this is across all organizations.

**Comment by ofedoren** [comment]
@lzap, sure it makes sense that if taxonomy support should be added then payload should consider resources/data to be within the same loc/org. Not sure what blocks us to add it now IF we consider adding it in the future.

Anyway, PR now add new roles only with few rubocop/API fixes.

**Comment by lzap** [comment]
I'd appreciate another opinion on this @adamruzicka (taxonomy).

**Review by lzap — APPROVED** [review]
Okay, a lot of small code improvements too.

**Comment by lzap** [comment]
Merged thanks, added note about docs: https://projects.theforeman.org/issues/31860

**Pull request merged**
