### PR TITLE
Fixes #31075 - Fix reference ::Webhook in ForemanWebhooks::EventSubscriber

### PR DESCRIPTION
**Pull request by kamils-iRonin**
@lzap I was able to reproduce the issue and it seems to fix it. Could you check if it works for you?

### CODE REVIEW

**Comment by ofedoren** [comment]
Even though it can fix the issue, the main issue, I guess, is that the models (and routes) are not properly scoped in this plugin..

**Comment by timogoebel** [comment]
> the main issue, I guess, is that the models (and routes) are not properly scoped in this plugin..

@ofedoren: Do you mind explaining this a little more? I can't follow. How can we solve this?

**Comment by kamils-iRonin** [comment]
I guess we should move models into `ForemanWebhooks` namespace (`Webhook` -> `ForemanWebhooks::Webhook`)

**Comment by timogoebel** [comment]
Makes sense. I'll go ahead and merge this one, we can fix the namespacing in a separate PR.

**Comment by lzap** [comment]
Wow thank you so much, I wonder why this fix the issue? I don't understand Rails autoloading much, if you could drop some reading for me that would be great. This is not the first time I've seen this.

**Pull request merged**
