### PR TITLE
Fixes #34988 - Refactor and use TableIndexPage from core

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by adamruzicka** [comment]
Looks good to me, although there are several inconsistencies with the rest of the ui.

When empty state is shown, on other pages we don't show the search bar and the empty state itself has a button to create a new $thing.

When the table is shown (ie, when there are records), the create new $thing button is on the right side.

I'm not saying one is better than the other, do you know if pf4 gives any guidance about this?

**Comment by ofedoren** [comment]
@adamruzicka, well I'm just using a template which is available in core, let's ask @MariaAga about that ^

**Comment by MariaAga** [comment]
Create new button is next to the search button because that was the new design given to me for new pages, probably to make room for a small pagination component later on the right side.
The search button - there are no guidelines from pf.

**Review by adamruzicka — CHANGES_REQUESTED** [review]
One last thing, the search bar offers autocompletion for hosts, which is not the best fit here.

**Comment by ofedoren** [comment]
> One last thing, the search bar offers autocompletion for hosts, which is not the best fit here.

Yeap, that's a bug in core: https://github.com/theforeman/foreman/pull/9267.

**Comment by ofedoren** [comment]
> Also if I have only one webhook and I remove it, the page does not go to empty state now until I explicitly refresh the page

Hmm, not sure how to reproduce it, because "it works on my machine" :/
a

**Comment by adamruzicka** [comment]
I must have been on old foreman or something, seems to work now when tested in conjunction with the autocomplete fix, nevermind then.

**Comment by adamruzicka** [comment]
Ah! I guess I know what I did
1) Have no webhooks
2) Create a webhook called foo
3) Search for `name = foo`
4) Remove it

Now you'll get an empty table. I'd vote for disregarding the search and showing the empty state if there are no webhooks at all, no matter the search, but that's probably just personal preference and I'm willing to let it as is

**Comment by ofedoren** [comment]
Thanks, @adamruzicka, the two related PRs were merged, I guess we can merge this one as well. Let's stick with the empty table.

**Pull request merged**
