### PR TITLE
Fixes #36910 - Expect ERB in URL for test webhook

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by adamruzicka** [comment]
The text alignment looks weird. Does it need to be centered?
image


Ftr here's how it looks on failure
image

**Comment by pondrejk** [comment]
Just from looking at the screenshots, the error message is now much more useful, I agree with text alignment not to be center

**Comment by ofedoren** [comment]
Thanks, @adamruzicka and @pondrejk, fixed the alignment:
ScreenShot-1699632115106

**Review by pondrejk — APPROVED** [review]

**Review by adamruzicka — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @ofedoren & @pondrejk !

**Pull request merged**
