### PR TITLE
Fix #30806 - added request/session headers

### PR DESCRIPTION
**Pull request by lzap**
Plus timeout. I am using setting from core. Ideally we should create a new one but this is okay I think.

### CODE REVIEW

**Review by ofedoren — APPROVED** [review]
Seems OK, thanks, @lzap!

**Comment by timogoebel** [comment]
@lzap: This needs a rebase, now.

**Comment by lzap** [comment]
Rebased, I added @ofedoren to the github repo with write access if you don't mind. This should be ready.

**Comment by ofedoren** [comment]
Thanks, @lzap, merging this one.

**Pull request merged**
