### PR TITLE
Fixes #37469 - Support Zeitwerk loader

### PR DESCRIPTION
**Pull request by ofedoren**
~WIP~

### CODE REVIEW

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman_webhooks/pull/77 should also provide EL 9 RPMs and use a RHEL buildroot.

**Comment by ekohl** [comment]
> #77 should also provide EL 9 RPMs and use a RHEL buildroot.

I think this may hit the bug where the buildroot for a PR isn't updated if you rebase it. Doesn't matter, it still produces the SRPM for me and I rebuild it in COPR anyway.

**Comment by ofedoren** [comment]
Ready to merge after https://github.com/theforeman/foreman/pull/10131 is merged, dropped the commit for testing with Foreman PR, the latest run was green:
Screenshot_20240903_143351

**Review by ekohl — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @ofedoren !

**Pull request merged**
