### PR TITLE
Fixes #35867 - Fix default Katello templates

### PR DESCRIPTION
**Pull request by jloeser**
Rendering of template fails with undefined method `action_output`.

### CODE REVIEW

**Review by sbernhard — CHANGES_REQUESTED** [review]
Looks like, this needs to be adapted to
https://github.com/theforeman/foreman-tasks/blob/master/app/models/foreman_tasks/task.rb#L95

which was changed from action_output to action_continuous_ouput in https://github.com/theforeman/foreman-tasks/commit/b904dcfad3878365177e644cf8c8caf7b05cf0f5

**Comment by jloeser** [comment]
Rendering is working now with `:action_continuous_output`. Thanks @sbernhard !

**Comment by sbernhard** [comment]
[test foreman_webhooks]

**Review by sbernhard — APPROVED** [review]

**Review by ofedoren — APPROVED** [review]
Thanks, @jloeser and @sbernhard, merging.

**Pull request merged**
